<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'SspContactTest\SampleTest'               => __DIR__ . '/tests/SspContact/SampleTest.php',
  'SspContactTest\Framework\TestCase'       => __DIR__ . '/tests/SspContact/Framework/TestCase.php',
  'SspContact\Module'                       => __DIR__ . '/Module.php',
  'SspContact\Factory\MailTransportFactory' => __DIR__ . '/src/SspContact/Factory/MailTransportFactory.php',
  'SspContact\Factory\ContactMapperFactory' => __DIR__ . '/src/SspContact/Factory/ContactMapperFactory.php',
  'SspContact\Mapper\Contact'               => __DIR__ . '/src/SspContact/Mapper/Contact.php',
  'SspContact\Mapper\ContactHydrator'       => __DIR__ . '/src/SspContact/Mapper/ContactHydrator.php',
  'SspContact\Form\ContactFilter'           => __DIR__ . '/src/SspContact/Form/ContactFilter.php',
  'SspContact\Form\ContactForm'             => __DIR__ . '/src/SspContact/Form/ContactForm.php',
  'SspContact\Mail\SspSendGridTransport'    => __DIR__ . '/src/SspContact/Mail/SspSendGridTransport.php',
  'SspContact\Controller\ContactController' => __DIR__ . '/src/SspContact/Controller/ContactController.php',
  'SspContact\Entity\Contact'               => __DIR__ . '/src/SspContact/Entity/Contact.php',
);
