<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SspContact\Controller\ContactController' => __DIR__ . '/src/SspContact/Controller/ContactController.php',
    'SspContact\Module'                       => __DIR__ . '/Module.php',
    'SspContactTest\SampleTest'               => __DIR__ . '/tests/SspContact/SampleTest.php',
    'SspContactTest\Framework\TestCase'       => __DIR__ . '/tests/SspContact/Framework/TestCase.php',
    'SspContact\Form\ContactForm'             => __DIR__ . '/src/SspContact/Form/ContactForm.php',
);
