<?php $this->headTitle()->append('Contact Us'); ?>
<?php
$contactForm = $this->form;
/* @var $contactForm \Zend\Form\Form */
$contactForm->prepare();
?>
<div class="container">

</div>
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span9">
                    <section id="block-download">
                        <div class="row-fluid">
                            <div class="span8">
                                <?php if ($contactForm->hasValidated() && !$contactForm->isValid()): ?>
                                    <div class="alert alert-error">
                                        <?php $elements = $contactForm->getElements(); ?>
                                        <?php foreach ($elements as $element): ?>
                                            <?php echo $this->formElementErrors($element); ?>
                                        <?php endforeach; ?>
                                    </div>
                                <?php endif; ?>
                                <?php echo $this->form()->openTag(
                                    $contactForm->setAttribute('class', 'form-horizontal')
                                ); ?>
                                <?php echo $this->arcControlGroup($contactForm->get('id')); ?>
                                <?php echo $this->arcControlGroup($contactForm->get('is_active')); ?>
                                <?php echo $this->arcControlGroup(
                                    $contactForm->get('first_name')->setAttribute('class', 'input-block-level')
                                ); ?>
                                <?php echo $this->arcControlGroup(
                                    $contactForm->get('last_name')->setAttribute('class', 'input-block-level')
                                ); ?>
                                <?php echo $this->arcControlGroup(
                                    $contactForm->get('email')->setAttribute('class', 'input-block-level')
                                ); ?>
                                <?php echo $this->arcControlGroup(
                                    $contactForm->get('subject')->setAttribute('class', 'input-block-level')
                                ); ?>
                                <?php echo $this->arcControlGroup(
                                    $contactForm->get('message')->setAttribute('class', 'input-block-level')
                                ); ?>
                                <?php echo $this->arcControlGroup($contactForm->get('human_test')); ?>
                                <div class="control-group">
                                    <div class="controls pull-right">
                                        <input type="submit" id="submit_contact" class="btn btn-primary"/>
                                    </div>
                                </div>
                                <?php echo $this->form()->closeTag($contactForm); ?>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="span3">
                    <div class="widget text-center" id="mc_embed_signup">
                        <form
                            action="http://uniquewebsites.us6.list-manage.com/subscribe/post?u=f6982e96ad914a99e45e6b5a9&amp;id=48ad0ac116"
                            method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                            class="validate form-signup-home fade-in three" target="_blank" novalidate>
                            <label for="mce-EMAIL">Signup for future notifications</label>
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL"
                                   placeholder="email address" required/>
                                        <span class="clear text-center clearfix">
                                            <input type="submit" value="Subscribe" name="subscribe"
                                                   id="mc-embedded-subscribe" class="button"/>
                                        </span>
                        </form>
                    </div>
                    <div class="widget" id="text-widget-1">
                        <h3>You missed it!</h3>

                        <p>The PHP community in South Florida organized a PHP developer conference in Miami,
                            and <strong>you missed it!</strong> We hosted some of the best <a
                                href="http://sunshinephp.com/schedule/speakers/" title="Speakers">speakers</a>, awesome <a
                                href="http://sunshinephp.com/schedule/talks/" title="Talk Topics">talk topics</a>,
                            latest technologies, and up to date news in PHP. And did we mention a Hackathon and
                            Uncon'ference?</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>