<div class="container">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span9">
                    <section id="block-download">
                        <ul class="breadcrumb">
                            <li><a href="/">Home</a> <span class="divider">/</span></li>
                            <li class="active">SunshinePHP Conference</li>
                        </ul>
                        <div class="hero-unit">
                            <h1>Thank you!</h1>
                            <p>Some one will get back to you as soon as possible</p>
                        </div>
                    </section>
                </div>
                <?php echo $this->sidebar(); ?>
            </div>
        </div>
    </div>
</div>